name: Anypoint CLI Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cli:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4
        
      - name: Print Account Details
        run: >
          anypoint-cli-v4 account:user:describe 
          --client_id ebc5078aaf434fc6ab2cd0df15372ba6
          --client_secret 37C10f90F2154b81A53201587B3bf843
          --organization b3875455-785b-461e-8239-06746330e0c6
          --environment Sandbox
          -o json
